# Perform Unity build for UnityClient project (Itch.io artifacts version)
# See more here:
# - https://game.ci/docs/github/builder
# - https://itch.io/docs/butler
name: Build UnityClient (Itch.io artifacts)

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL # WebGL
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: UnityClient
          versioning: Semantic
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload to Itch.io using Butler
        run: ./butler push --verbose \"build/${{ matrix.targetPlatform }}\" konh/unknownspace:html
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}